Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2018-04, with the labels that each got.

#2843 Added ScriptContext for Python APIs called from DataFilter scripts
  src/Charts/PythonChart.cpp
  src/Core/DataFilter.cpp
  src/Core/DataFilter.h
  src/Core/Specification.cpp
  src/Core/Specification.h
  src/Metrics/RideMetric.cpp
  src/Metrics/UserMetric.cpp
  src/Python/PythonEmbed.cpp
  src/Python/PythonEmbed.h
  src/Python/SIP/Bindings.cpp
Labels: P2, metrics request

#2850 TriScore - On zero fallback to TRIMP Zonal Points for HR base score
  src/Metrics/RideMetric.cpp
  src/Metrics/SwimScore.cpp
Labels: P2, metrics request

#2856 Add Lap Distance and Lap Distance Remaining dials and telemetry
  src/Train/DialWindow.cpp
  src/Train/ErgFile.cpp
  src/Train/ErgFile.h
  src/Train/RealtimeData.cpp
  src/Train/RealtimeData.h
  src/Train/TrainSidebar.cpp
  src/Train/TrainSidebar.h
Labels: P3, chart type request, training view

#2858 Ensure the Cloud Service wizard on top after the OAuth modal dialog closes
  src/Cloud/AddCloudWizard.cpp
Labels: P2, gui / cosmetic error

#2859 Correct the link to the user list
  CONTRIBUTING.md
Labels: documentation
