Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2018-03, with the labels that each got.

#2806 Imagic extended
  src/Charts/HomeWindow.cpp
  src/Charts/HomeWindow.h
  src/Core/Context.h
  src/Core/Settings.h
  src/Resources/application.qrc
  src/Resources/images/devices/imagic.png
  src/Train/AddDeviceWizard.cpp
  src/Train/AddDeviceWizard.h
  src/Train/DeviceTypes.cpp
  src/Train/DeviceTypes.h
  src/Train/EzUsb.c
  src/Train/EzUsb.h
  src/Train/Imagic.cpp
  src/Train/Imagic.h
  src/Train/ImagicController.cpp
  src/Train/ImagicController.h
  src/Train/LibUsb.cpp
  src/Train/LibUsb.h
  src/Train/TrainSidebar.cpp
  src/Train/TrainSidebar.h
  src/src.pro
Labels: P1, device support request, training view

#2794 Added Tooltips with metrics descriptions to RideSummary
  src/Charts/RideSummaryWindow.cpp
  src/Charts/RideSummaryWindow.h
  src/Gui/Colors.cpp
Labels: P3, documentation, metrics request

#2812 Deprecate Bing Map and set default tile server URL for new OSM maps
  src/Charts/RideMapWindow.cpp
  src/Charts/RideMapWindow.h
  src/Gui/GcWindowRegistry.cpp
Labels: P1, platform support error

#2815 TCX Export
  src/FileIO/TcxRideFile.cpp
Labels: file format error

#2821 Body & HRV Measures - MacOS
  src/Cloud/BodyMeasuresDownload.cpp
  src/Cloud/HrvMeasuresDownload.cpp
Labels: UX, platform support error

#2822 Update Translation DE - Part 3
  src/Resources/translations/gc_de.ts
Labels: translation

#2805 LTMSidebar: Load most recently selected phase on GC start
  src/Gui/LTMSidebar.cpp
Labels: UX

#2826 Fixed LTM Chart to show Events on Phases and Season end date
  src/Charts/LTMPlot.cpp
Labels: P2, bug, charting error

#2827 Fixed crashes on edit/delete events when a phase is selected
  src/Gui/LTMSidebar.cpp
Labels: crash

#2825 Cloud Upload/Sync - check for unsaved activities
  src/Cloud/CloudService.cpp
  src/Cloud/CloudService.h
  src/Gui/MainWindow.cpp
Labels: cloud
