Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2018-10, with the labels that each got.

#2946 Build without ical
  src/Gui/LTMSidebar.cpp
  src/src.pro
Labels: build error

#2950 Enable libusb and libusb-compat
  .travis.yml
Labels: CI, P2, build error

#2948 Translation
  src/Gui/AnalysisSidebar.cpp
  src/Resources/translations/gc_de.ts
Labels: translation
