Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2019-12, with the labels that each got.

#3225 Strava data
  src/Cloud/Strava.cpp
Labels: cloud

#2951 Python data processors
  src/Charts/PythonChart.cpp
  src/Charts/PythonChart.h
  src/Charts/RideEditor.cpp
  src/Charts/RideEditor.h
  src/Core/main.cpp
  src/FileIO/DataProcessor.cpp
  src/FileIO/DataProcessor.h
  src/FileIO/FixPyDataProcessor.cpp
  src/FileIO/FixPyDataProcessor.h
  src/FileIO/FixPyRunner.cpp
  src/FileIO/FixPyRunner.h
  src/FileIO/FixPyScript.h
  src/FileIO/FixPyScriptsDialog.cpp
  src/FileIO/FixPyScriptsDialog.h
  src/FileIO/FixPySettings.cpp
  src/FileIO/FixPySettings.h
  src/Gui/MainWindow.cpp
  src/Gui/MainWindow.h
  src/Gui/Pages.cpp
  src/Python/PythonEmbed.h
  src/Python/SIP/Bindings.cpp
  src/Python/SIP/Bindings.h
  src/Python/SIP/goldencheetah.sip
  src/Python/SIP/sipAPIgoldencheetah.h
  src/Python/SIP/sipgoldencheetahBindings.cpp
  src/Python/SIP/sipgoldencheetahPythonDataSeries.cpp
  src/Python/SIP/sipgoldencheetahPythonXDataSeries.cpp
  src/Python/SIP/sipgoldencheetahQString.cpp
  src/Python/SIP/sipgoldencheetahcmodule.cpp
  src/src.pro
Labels: P1

#3275 Fix Issue 3273: Busy Hang in FixDeriveDistance
  src/FileIO/FixDeriveDistance.cpp
Labels: bug, crash
