Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2019-02, with the labels that each got.

#3014 Prevent GC from crashing if Bindings method return NULL PythonDataSeries
  src/Python/SIP/Bindings.cpp
Labels: P0, crash, metrics error

#3016 Translation Fix
  src/Resources/translations/gc_de.ts
Labels: translation

#3018 Ignore MSVC2017 build artifacts
  .gitignore
Labels: build
