Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2019-11, with the labels that each got.

#3209 Fixed BTLE Pair page in AddDeviceWizard to avoid ANT+ dependence
  src/Train/AddDeviceWizard.cpp
  src/Train/AddDeviceWizard.h
  src/Train/BT40Device.cpp
  src/Train/BT40Device.h
Labels: P1, device support error, training view

#3215 Add new sources for video-layout.xml meters
  src/Train/VideoWindow.cpp
Labels: P2, gui / workflow request, training view

#3217 Update Translation DE
  src/Resources/translations/gc_de.ts
Labels: translation

#3226 Today's Plan Download
  src/Cloud/TodaysPlan.cpp
Labels: P3

#3228 3227: Further optimize trends tracker table display
  src/Charts/LTMPlot.cpp
  src/Charts/LTMWindow.cpp
  src/Metrics/PaceZones.cpp
Labels: P2, performance, refactoring

#3231 Issue 3230: Train mode compute altitude from slope
  src/Train/ErgFile.cpp
  src/Train/TrainSidebar.cpp
Labels: P2, feature request, training view

#3233 Add support for Device symbol on filters but disable set/unset/isset
  src/Core/DataFilter.cpp
Labels: Expressions & Scripting, P3, bug
