Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2019-04, with the labels that each got.

#3063 Aerolab buffer fix
  src/Charts/Aerolab.cpp
Labels: P1, crash

#3066 Gpx location cleanup
  src/Train/DialWindow.cpp
Labels: P3, gui / cosmetic error

#3015 Fixes: #3007 by specifying HFS+ for fs type
  travis/osx/after_success.sh
Labels: P3, build error

#2995 xdata: Fix min/max of spinbox in xdata editor
  src/Charts/RideEditor.cpp
Labels: P2, gui / cosmetic error

#2914 Change GPX decimal separator to dot
  src/FileIO/GpxRideFile.cpp
Labels: file format error
