Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2020-05, with the labels that each got.

#3443 Teach elevation widget to honor skipping
  src/Train/MeterWidget.cpp
  src/Train/RealtimeData.cpp
  src/Train/RealtimeData.h
  src/Train/TrainSidebar.cpp
  src/Train/VideoWindow.cpp
Labels: P2, feature request, training view

#3458 MeterWidgets must move / hide when main window is moved / minimized
  src/Gui/MainWindow.cpp
  src/Gui/MainWindow.h
  src/Train/VideoWindow.cpp
  src/Train/VideoWindow.h
Labels: P3, gui / cosmetic error, training view

#3462 Clip the Meter Widgets to the visible portion of the Video Window
  src/Train/MeterWidget.cpp
  src/Train/MeterWidget.h
  src/Train/VideoLayoutParser.cpp
Labels: P2, gui / cosmetic error, training view

#3464 Remove Conditional Compilation for Qt < 5.9
  INSTALL-LINUX
  INSTALL-MAC
  INSTALL-WIN32
  src/Charts/AllPlot.h
  src/Charts/AllPlotWindow.cpp
  src/Charts/DiaryWindow.cpp
  src/Charts/GoldenCheetah.cpp
  src/Charts/HomeWindow.cpp
  src/Charts/LTMPopup.cpp
  src/Charts/LTMWindow.cpp
  src/Charts/LogTimeScaleDraw.cpp
  src/Charts/PythonChart.cpp
  src/Charts/RideMapWindow.cpp
  src/Charts/RideSummaryWindow.cpp
  src/Charts/RideSummaryWindow.h
  src/Cloud/CalDAV.cpp
  src/Cloud/OAuthDialog.cpp
  src/Cloud/OAuthDialog.h
  src/Cloud/Strava.cpp
  src/Cloud/TodaysPlan.cpp
  src/Cloud/TrainingsTageBuch.cpp
  src/Cloud/TrainingsTageBuch.h
  src/Cloud/Velohero.cpp
  src/Cloud/WithingsDownload.cpp
  src/Cloud/Xert.cpp
  src/Core/RideCache.h
  src/Core/Settings.h
  src/Core/main.cpp
  src/FileIO/AthleteBackup.cpp
  src/Gui/AnalysisSidebar.cpp
  src/Gui/ComparePane.cpp
  src/Gui/MainWindow.cpp
  src/Gui/MainWindow.h
  src/Gui/MergeActivityWizard.cpp
  src/Gui/Pages.cpp
  src/Gui/Pages.h
  src/Gui/RideNavigator.cpp
  src/R/RLibrary.h
  src/Train/AddDeviceWizard.cpp
  src/Train/AddDeviceWizard.h
  src/Train/DeviceTypes.cpp
  src/Train/TrainBottom.cpp
  src/Train/TrainSidebar.cpp
  src/Train/VideoWindow.cpp
  src/Train/VideoWindow.h
  src/Train/WorkoutWidget.cpp
  src/Train/WorkoutWizard.cpp
  src/src.pro
Labels: P2, refactoring
