Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2020-01, with the labels that each got.

#3287 Today'sPlan Integration
  src/Cloud/TodaysPlan.cpp
Labels: multisport

#2837 Improve RLV Syncronization
  src/Train/ErgFile.cpp
  src/Train/TrainSidebar.cpp
  src/Train/VideoSyncFile.cpp
  src/Train/VideoWindow.cpp
Labels: P2, training view

#3298 Remove ampersand from menu and button text before compare
  src/Charts/HomeWindow.cpp
  src/Gui/MainWindow.cpp
  src/Gui/RideImportWizard.cpp
Labels: P2, platform support error

#3300 Add Garmin Instinct device ID
  src/FileIO/FitRideFile.cpp
Labels: P3, device support request, file format request

#3307 Add garmin products
  src/FileIO/FitRideFile.cpp
Labels: P3, device support request

#3312 Add ANT+ product info
  src/FileIO/FitRideFile.cpp
Labels: P3, device support request

#3313 Allow Estimate Distance to run automatically without crash
  src/Core/Settings.h
  src/FileIO/FixDeriveDistance.cpp
Labels: P0, bug, crash

#3310 Issue 3302: BSpline altitude smoothing to FixGPS.
  src/Core/Settings.h
  src/FileIO/DataProcessor.cpp
  src/FileIO/DataProcessor.h
  src/FileIO/FilterHRV.cpp
  src/FileIO/FixAeroPod.cpp
  src/FileIO/FixDeriveDistance.cpp
  src/FileIO/FixDeriveHeadwind.cpp
  src/FileIO/FixDerivePower.cpp
  src/FileIO/FixDeriveTorque.cpp
  src/FileIO/FixElevation.cpp
  src/FileIO/FixFreewheeling.cpp
  src/FileIO/FixGPS.cpp
  src/FileIO/FixGaps.cpp
  src/FileIO/FixHRSpikes.cpp
  src/FileIO/FixLapSwim.cpp
  src/FileIO/FixMoxy.cpp
  src/FileIO/FixPower.cpp
  src/FileIO/FixPyDataProcessor.cpp
  src/FileIO/FixPyDataProcessor.h
  src/FileIO/FixRunningCadence.cpp
  src/FileIO/FixRunningPower.cpp
  src/FileIO/FixSmO2.cpp
  src/FileIO/FixSpeed.cpp
  src/FileIO/FixSpikes.cpp
  src/FileIO/FixTorque.cpp
  src/FileIO/GeometricTools_BSplineCurve.h
  src/FileIO/RideFile.cpp
  src/FileIO/Snippets.cpp
Labels: P1, feature request, function request

#3323 Fix import of HRV from Fit files where single records occur
  src/FileIO/FitRideFile.cpp
  test/runs/Move_2020_01_15_19_27_16_Running.fit
Labels: P2, file format error

#3324 Add support for Ergofit Bike
  src/Resources/images/devices/ergofit_home400.png
  src/Train/AddDeviceWizard.cpp
  src/Train/AddDeviceWizard.h
  src/Train/DeviceTypes.cpp
  src/Train/DeviceTypes.h
  src/Train/Ergofit.cpp
  src/Train/Ergofit.h
  src/Train/ErgofitConnection.cpp
  src/Train/ErgofitConnection.h
  src/Train/ErgofitController.cpp
  src/Train/ErgofitController.h
  src/Train/TrainSidebar.cpp
  src/src.pro
Labels: P1, device support request
