Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2020-04, with the labels that each got.

#2678 QwtPlotGappedCurve: Include the last point in the plot
  qtsolutions/qwtcurve/qwt_plot_gapped_curve.cpp
Labels: P3, charting error

#3420 AppVeyor - Don't use parallel build for QWT
  appveyor.yml
Labels: CI, build

#3401 Enable BT on Windows
  src/Train/BT40Device.cpp
  src/Train/DeviceTypes.cpp
Labels: P1, device support request

#3414 VMPro: Add possibility to start calibration manually
  src/Train/VMProConfigurator.cpp
  src/Train/VMProConfigurator.h
  src/Train/VMProWidget.cpp
Labels: P2, device support request, training view

#3423 Fix indexing bugs in the original TTS code
  src/FileIO/TTSReader.cpp
  src/Train/ErgFile.cpp
Labels: crash, file format error

#3411 Elevation and grade gidgets
  src/Resources/xml/video-layout.xml
  src/Train/MeterWidget.cpp
  src/Train/MeterWidget.h
  src/Train/VideoLayoutParser.cpp
  src/Train/VideoWindow.cpp
Labels: P2, function request, training view
