Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2020-08, with the labels that each got.

#3485 Windows builds log to goldencheetah.log when not debugging
  src/Core/main.cpp
Labels: O/S error, P1, feature request

#3564 Generalize Body/Hrv Measures and add Nutrition data as example
  doc/user/measures.ini
  doc/user/nutrition-data-example.csv
  src/Cloud/HrvMeasuresDownload.cpp
  src/Cloud/HrvMeasuresDownload.h
  src/Cloud/MeasuresDownload.cpp
  src/Cloud/MeasuresDownload.h
  src/Cloud/TodaysPlanBodyMeasures.cpp
  src/Cloud/TodaysPlanBodyMeasures.h
  src/Cloud/WithingsDownload.cpp
  src/Cloud/WithingsDownload.h
  src/Core/APIWebService.cpp
  src/Core/BodyMeasures.cpp
  src/Core/BodyMeasures.h
  src/Core/HrvMeasures.cpp
  src/Core/HrvMeasures.h
  src/Core/Measures.cpp
  src/Core/Measures.h
  src/Core/RideItem.cpp
  src/Core/RideItem.h
  src/FileIO/BodyMeasuresCsvImport.cpp
  src/FileIO/FilterHRV.cpp
  src/FileIO/HrvMeasuresCsvImport.h
  src/FileIO/MeasuresCsvImport.cpp
  src/FileIO/MeasuresCsvImport.h
  src/Gui/ConfigDialog.cpp
  src/Gui/ConfigDialog.h
  src/Gui/HelpWhatsThis.h
  src/Gui/MainWindow.cpp
  src/Gui/MainWindow.h
  src/Gui/Pages.cpp
  src/Gui/Pages.h
  src/Metrics/BasicRideMetrics.cpp
  src/Metrics/HrvMetrics.cpp
  src/Python/PythonEmbed.h
  src/Resources/application.qrc
  src/Resources/ini/measures.ini
  src/src.pro
Labels: P1, feature request

#3538 Computrainer Button tidy up
  src/Train/ComputrainerController.cpp
  src/Train/ComputrainerController.h
  src/Train/TrainSidebar.cpp
  src/Train/TrainSidebar.h
Labels: device support request, training view

#3500 Propagate Weight and other simulation parameters to training devices
  src/Train/BT40Controller.cpp
  src/Train/BT40Controller.h
  src/Train/BT40Device.cpp
  src/Train/BicycleSim.h
  src/Train/FortiusController.cpp
  src/Train/FortiusController.h
  src/Train/ImagicController.cpp
  src/Train/ImagicController.h
  src/Train/RealtimeController.h
  src/Train/TrainSidebar.cpp
Labels: P2, device support request, training view
