Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2020-03, with the labels that each got.

#3331 Fix issue with font being "white on white" in dark-mode on Mac
  src/Charts/BlankState.cpp
Labels: P3, gui / cosmetic error

#3332 Derived stats for sim bicycle config screen
  src/Gui/Pages.cpp
  src/Gui/Pages.h
  src/Train/BicycleSim.h
Labels: P2, training view

#3349 Optimize splines and bikesim dvdt.
  src/FileIO/FixGPS.cpp
  src/FileIO/LocationInterpolation.cpp
  src/FileIO/LocationInterpolation.h
  src/Train/BicycleSim.cpp
  src/Train/BicycleSim.h
  src/Train/PhysicsUtility.cpp
Labels: P2, statistics & maths
