Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2020-09, with the labels that each got.

#3595 Fortius fixes
  src/Train/Fortius.cpp
Labels: P2, device support error, training view

#3599 Altitude smoothing fixes
  src/FileIO/FixGPS.cpp
Labels: P3, bug

#3600 Lat and Lon now get DegreesToRadians
  src/FileIO/FixDerivePower.cpp
  src/FileIO/FixRunningPower.cpp
  src/FileIO/LocationInterpolation.cpp
  src/FileIO/LocationInterpolation.h
Labels: P2, metrics error

#3604 Followup to 3599: Preserve Endpoints when Route Smoothing
  src/FileIO/FixGPS.cpp
  src/FileIO/LocationInterpolation.h
Labels: P3, bug
