Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2020-11, with the labels that each got.

#3573 Fix issue 3571: segment matching
  src/Core/Route.cpp
Labels: P3, bug

#3661 Sort routes when they are added to an activity
  src/Core/IntervalItem.h
  src/Core/RideItem.cpp
Labels: P3, gui / workflow request

#3546 make the date range of relative seasons (e.g. in Trends) update as time passes
  src/Charts/CriticalPowerWindow.cpp
  src/Core/Season.cpp
  src/Core/Season.h
  src/Core/SeasonParser.cpp
  src/Gui/AthletePages.cpp
  src/Gui/CompareDateRange.h
  src/Gui/ComparePane.cpp
  src/Gui/LTMSidebar.cpp
  src/Python/SIP/Bindings.cpp
  src/R/RTool.cpp
Labels: P2, bug, home view

#3662 Fix issues 3580, 3582
  src/Train/TrainSidebar.cpp
Labels: P3, bug, training view

#3663 Fix 3498 - truncate distances for display
  src/Train/DialWindow.cpp
Labels: P3, gui / cosmetic error, training view

#3664 Fix 3596: Fix display of route elevation.
  src/Train/ErgFile.cpp
  src/Train/ErgFile.h
  src/Train/MeterWidget.cpp
  src/Train/MeterWidget.h
Labels: P3, gui / cosmetic error, training view

#3114 Workout: Save LAP markers in mrc files
  src/Train/ErgFile.cpp
Labels: P3, file format error, training view

#3668 Teach ttsreader to process routes and segments
  src/FileIO/TTSReader.cpp
  src/FileIO/TTSReader.h
  src/Train/ErgFile.cpp
  src/Train/ErgFile.h
  src/Train/TrainSidebar.cpp
Labels: P3, file format request, training view

#3665 Add ~Mercator projection to overviewitem route
  src/Charts/OverviewItems.cpp
Labels: P3, gui / cosmetic error

#3673 Fix3672 - Read out of range when tts has 0 points
  src/FileIO/TTSReader.cpp
Labels: P3, file format error, training view

#3670 Fix3669 - Don't copy dual mode files twice.
  src/Train/Library.cpp
Labels: P3, bug, training view

#3653 Rotational Inertial for Custom Virtual Power
  src/ANT/ANT.cpp
  src/Train/AddDeviceWizard.cpp
  src/Train/AddDeviceWizard.h
  src/Train/BT40Controller.cpp
  src/Train/BicycleSim.cpp
  src/Train/DeviceConfiguration.h
  src/Train/Integrator.h
  src/Train/PolynomialRegression.cpp
  src/Train/PolynomialRegression.h
  src/Train/RealtimeController.cpp
  src/Train/RealtimeController.h
  src/Train/RealtimeData.cpp
  src/Train/RealtimeData.h
Labels: P2, device support request, feature request

#3678 Fix 3677: Slope Mode Lap Bugs
  src/Train/ErgFile.cpp
  src/Train/ErgFile.h
  src/Train/TrainSidebar.cpp
  src/Train/TrainSidebar.h
Labels: P3, bug, training view

#3470 Trim TCX files before importing
  src/FileIO/TcxRideFile.cpp
Labels: P3, file format request
