Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2020-12, with the labels that each got.

#3686 Fix 3685: Readable Segments in ErgFileOverview
  src/FileIO/TTSReader.cpp
  src/Train/ErgFile.cpp
  src/Train/ErgFile.h
  src/Train/ErgFilePlot.cpp
Labels: P3, gui / cosmetic error, training view

#3690 Daum: Fix signed byte issues
  src/Train/Daum.cpp
Labels: P3, device support error, training view

#3691 Daum: Adapt code for 8008 TRS pro
  src/Train/Daum.cpp
  src/Train/Daum.h
Labels: P2, device support request, training view

#3692 Daum minor code cleanup
  src/Train/Daum.cpp
  src/Train/Daum.h
  src/Train/DaumController.cpp
  src/Train/DaumController.h
Labels: P3, refactoring

#3695 Makefile that captures details on how to build GC on raspberry pis
  util/rpi/52-garmin-usb.rules
  util/rpi/Makefile.rpi
  util/rpi/README.md
  util/rpi/create_icon.sh
  util/rpi/gcconfig.pri.for_rpi
Labels: build

#3699 Simulated Hypoxia for Train Mode
  src/Core/Settings.h
  src/Gui/Pages.cpp
  src/Gui/Pages.h
  src/Train/BicycleSim.cpp
  src/Train/BicycleSim.h
  src/Train/TrainSidebar.cpp
Labels: P2, feature request, training view

#3705 Build warnings
  src/Train/MultiRegressionizer.h
  src/Train/PolynomialRegression.cpp
  src/Train/PolynomialRegression.h
Labels: P3, build, refactoring

#3704 Fix 3702: VideoSync Errors
  src/Train/VideoWindow.cpp
  src/Train/VideoWindow.h
Labels: P3, file format error, training view

#3711 Fix 3710:Geoloc double to string precision
  src/FileIO/FixElevation.cpp
  src/Train/LiveMapWebPageWindow.cpp
  src/Train/MeterWidget.cpp
Labels: P3, gui / cosmetic error, translation

#3709 Add Measures configuration to General Settings
  src/Core/Athlete.cpp
  src/Core/Measures.cpp
  src/Core/Measures.h
  src/Core/RideItem.cpp
  src/Gui/ConfigDialog.cpp
  src/Gui/ConfigDialog.h
  src/Gui/HelpWhatsThis.h
  src/Gui/Pages.cpp
  src/Gui/Pages.h
  src/Resources/application.qrc
  src/Resources/ini/measures.ini
Labels: P1, feature request

#3713 Fix 3712: Simulated Speed setting now honored in Ergo Mode.
  src/Gui/Pages.cpp
  src/Train/TrainSidebar.cpp
Labels: P2, feature request, training view

#3714 Redo bicyclesim settings layout and typos.
  src/Gui/Pages.cpp
Labels: P3, gui / cosmetic error

#3722 Screenshots of training views for the wiki
  doc/wiki/Chart_Live_Map.png
  doc/wiki/Chart_Pedal_Stroke.png
  doc/wiki/Chart_Realtime.png
  doc/wiki/Chart_Telemetry.png
  doc/wiki/Chart_Video_Player_Graphical_Meters.png
  doc/wiki/Chart_Video_Player_Text_Meters.png
  doc/wiki/Chart_Workout.png
  doc/wiki/Chart_Workout_Editor.png
Labels: documentation

#3730 Fix 3729: handle tts videosync distance outliers
  src/Train/ErgFile.cpp
Labels: P3, file format error, training view
