Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2020-10, with the labels that each got.

#3633 Remove modal dialog for Fortius disconnect
  src/Train/FortiusController.cpp
  src/Train/FortiusController.h
Labels: P2, device support request, training view

#3634 Fix a small issue in setPowerScaleFactor
  src/Train/Fortius.cpp
Labels: P2, device support error, training view

#3643 Fix Error Setting Custom Wheel Diameter
  src/Train/AddDeviceWizard.cpp
Labels: P3, bug, training view

#3636 Support Kurt Kinetic Inride and SmartControl
  src/Train/BT40Controller.cpp
  src/Train/BT40Controller.h
  src/Train/BT40Device.cpp
  src/Train/BT40Device.h
  src/Train/CalibrationData.cpp
  src/Train/CalibrationData.h
  src/Train/Kurt_SmartControl.cpp
  src/Train/Kurt_SmartControl.h
  src/Train/Kurt_inRide.cpp
  src/Train/Kurt_inRide.h
  src/Train/TrainSidebar.cpp
  src/src.pro
Labels: P2, device support request, training view
