Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2021-02, with the labels that each got.

#3818 trainer capabilities request fix
  src/ANT/ANTMessage.cpp
Labels: P2, device support error, training view

#3823 Workout: LiveMapWidget in video layout starts with the zoom specified in video-layout.xml
  src/Train/MeterWidget.cpp
Labels: P3, bug, training view

#3825 Fixes activity start time for imported iBike CSV files is incorrect
  src/FileIO/CsvRideFile.cpp
Labels: P3, file format error

#3764 Fix VLC Hangs with Intentional State and Ordered Async Dispatch
  src/Train/VideoWindow.cpp
  src/Train/VideoWindow.h
Labels: P3, platform support error, training view

#3745 Correctly recognize the Sigmasport iD.FREE product
  src/FileIO/FitRideFile.cpp
Labels: P3, device support request
