Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2021-01, with the labels that each got.

#3758 Correct spelling mistake
  README.md
Labels: documentation error

#3775 Daum: Improve support for more cockpits
  src/Train/Daum.cpp
  src/Train/Daum.h
Labels: P3, device support request, training view

#3776 Trainer Work Part 1: Move manual modes onto common load timer path.
  src/Train/TrainSidebar.cpp
Labels: refactoring, training view

#3785 Initial correction of force/speed/power calculations for Fortius
  src/Train/Fortius.cpp
  src/Train/Fortius.h
  src/Train/FortiusController.cpp
  src/Train/FortiusController.h
Labels: P2, device support error, training view

#3790 Fortius calibration
  src/Core/Settings.h
  src/Train/CalibrationData.h
  src/Train/Fortius.cpp
  src/Train/Fortius.h
  src/Train/FortiusController.cpp
  src/Train/FortiusController.h
  src/Train/TrainSidebar.cpp
Labels: P2, device support request, training view

#3732 LibUsb::OpenFortius - Remove call to usb_set_altinterface()
  src/Train/LibUsb.cpp
Labels: P3, platform support error, training view

#3795 Fortius USB timing
  src/Train/Fortius.cpp
Labels: P3, device support error, training view

#3800 RealtimeController::setWindResistance() should be passed CdARho, not just CdA
  src/Train/BicycleSim.h
  src/Train/Fortius.cpp
  src/Train/Fortius.h
  src/Train/TrainSidebar.cpp
Labels: P3, device support error, training view

#3801 Fix the request - reply interactions with the Fortius
  src/Train/Fortius.cpp
  src/Train/Fortius.h
  src/Train/FortiusController.cpp
Labels: P3, device support error, training view

#3806 Get the Altitude for CRS files even when Fast Forwarding
  src/Train/ErgFile.cpp
  src/Train/ErgFile.h
  src/Train/TrainSidebar.cpp
Labels: P3, bug, training view

#3804 Fortius "rolling" calibration
  src/Train/Fortius.cpp
  src/Train/Fortius.h
  src/Train/FortiusController.cpp
  src/Train/TrainSidebar.cpp
Labels: P3, device support request, training view
