Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2021-03, with the labels that each got.

#3836 Enable Athlete Open menu to allow creation of new athletes
  src/Gui/AthleteView.cpp
  src/Gui/AthleteView.h
  src/Gui/MainWindow.cpp
  src/Gui/MainWindow.h
Labels: P2, gui / workflow request

#3845 Insure that Web pages are deleted before the Web Profile
  src/Charts/LTMWindow.cpp
  src/Charts/PythonChart.cpp
  src/Charts/PythonChart.h
  src/Charts/RideMapWindow.cpp
  src/Charts/RideSummaryWindow.cpp
  src/Cloud/OAuthDialog.cpp
  src/Cloud/OAuthDialog.h
  src/Core/GcUpgrade.cpp
  src/Core/GcUpgrade.h
  src/Gui/GcCrashDialog.cpp
  src/Gui/GcCrashDialog.h
  src/Train/LiveMapWebPageWindow.cpp
  src/Train/WebPageWindow.cpp
Labels: P3, bug

#3843 Remember SRM offset from last successful calibration
  src/ANT/ANTChannel.cpp
  src/Core/Settings.h
Labels: P3, feature request, training view

#3847 Compute the altitude incrementally from slope for Manual Slope Mode
  src/Train/TrainSidebar.cpp
Labels: P3, feature request, training view
