Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2024-09, with the labels that each got.

#4545 Removed wildcard from translatable part
  src/Gui/AthletePages.cpp
  src/Gui/NewCyclistDialog.cpp
  src/Resources/translations/gc_cs.ts
  src/Resources/translations/gc_de.ts
  src/Resources/translations/gc_es.ts
  src/Resources/translations/gc_fr.ts
  src/Resources/translations/gc_it.ts
  src/Resources/translations/gc_nl.ts
  src/Resources/translations/gc_ru.ts
  src/Resources/translations/gc_sv.ts
  src/Resources/translations/gc_zh-cn.ts
  src/Resources/translations/gc_zh-tw.ts
Labels: translation, bug, P3

#4547 Add Morpheus M7 heart rate monitor
  util/fit/nongarmin.json
Labels: device support request, P3

#4534 Implemented user defined relative date ranges
  .gitignore
  build.pro
  src/Charts/CriticalPowerWindow.cpp
  src/Charts/CriticalPowerWindow.h
  src/Charts/HistogramWindow.h
  src/Charts/LTMPlot.cpp
  src/Charts/LTMTool.cpp
  src/Charts/LTMTool.h
  src/Charts/LTMWindow.cpp
  src/Charts/TreeMapWindow.h
  src/Core/Athlete.cpp
  src/Core/DataFilter.cpp
  src/Core/Season.cpp
  src/Core/Season.h
  src/Core/SeasonDialogs.cpp
  src/Core/SeasonDialogs.h
  src/Core/SeasonParser.cpp
  src/Core/SeasonParser.h
  src/Core/Seasons.cpp
  src/Core/Seasons.h
  src/Gui/AthletePages.cpp
  src/Gui/AthletePages.h
  src/Gui/ComparePane.cpp
  src/Gui/LTMSidebar.cpp
  src/Gui/LTMSidebar.h
  src/Gui/Pages.h
  src/Metrics/PMCData.cpp
  src/Python/SIP/Bindings.cpp
  src/R/RTool.cpp
  src/src.pro
  unittests/season/season.pro
  unittests/season/testSeason.cpp
  unittests/seasonOffset/seasonOffset.pro
  unittests/seasonOffset/testSeasonOffset.cpp
  unittests/seasonParser/seasonParser.pro
  unittests/seasonParser/seasons.xml
  unittests/seasonParser/testSeasonParser.cpp
  unittests/unittests.pri.in
  unittests/unittests.pro
Labels: feature request, P2
