Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2024-12, with the labels that each got.

#4580 Update Spanish translation
  src/Resources/translations/gc_es.ts
Labels: translation

#4582 Text in Trainbottom window is word wrapped (Training Window)
  src/Train/TrainBottom.cpp
Labels: gui / cosmetic error, training view

#4584 Fixed calculation of measures when using imperial units
  src/Gui/AthletePages.cpp
Labels: bug, P3

#4585 Fixed compilation error when python is disabled
  src/Gui/Pages.cpp
Labels: compile error

#4583 Assigned keyboard shortcuts to toggle sidebars
  src/Gui/MainWindow.cpp
Labels: gui / workflow request, P3
