Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2024-06, with the labels that each got.

#4510 Added screenshots for wiki-documentation
  doc/wiki/PreferencesTrainingWorkoutTags.png
  doc/wiki/SideBar_Train_WorkoutInfo.png
  doc/wiki/SideBar_Train_WorkoutInfo_Collapsed.png
  doc/wiki/SideBar_Train_WorkoutInfo_Expanded.png
  doc/wiki/SideBar_Train_Workout_Filter.png
Labels: documentation

#4511 Dialwindow font scaling (v2)
  src/Core/Settings.h
  src/Gui/Pages.cpp
  src/Gui/Pages.h
  src/Train/DialWindow.cpp
  src/Train/DialWindow.h
  src/Train/ScalingLabel.cpp
  src/Train/ScalingLabel.h
  src/src.pro
Labels: training view, feature request, P2

#4515 ErgFileplot: Updating the zone-coloring on changed intensity
  src/Core/Context.h
  src/Train/ErgFilePlot.cpp
  src/Train/ErgFilePlot.h
  src/Train/TrainBottom.cpp
  src/Train/TrainSidebar.cpp
  src/Train/TrainSidebar.h
Labels: chart type request, training view, P2

#4517 Add tool tips to trainer controls
  src/Core/Settings.h
  src/Gui/Pages.cpp
  src/Gui/Pages.h
  src/Train/TrainBottom.cpp
  src/Train/TrainBottom.h
Labels: gui / cosmetic error, P3
