Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2024-05, with the labels that each got.

#4483 Qt6: Preventing crash in stacked LTMPlots
  src/Charts/LTMWindow.cpp
Labels: QT6 Refactor

#4469 DialWindow: Scaling font in both dimensions
  src/Train/DialWindow.cpp
  src/Train/DialWindow.h
  src/Train/ScalingLabel.cpp
  src/Train/ScalingLabel.h
  src/src.pro
Labels: charting error, training view, P2

#4487 Update Spanish translation
  src/Resources/translations/gc_es.ts
Labels: translation

#4488 Qt6: The signature of enterEvent changed
  src/Charts/GcPane.cpp
  src/Charts/GcPane.h
  src/Charts/GoldenCheetah.cpp
  src/Charts/GoldenCheetah.h
Labels: QT6 Refactor

#4493 Add close button to manage filters
  src/Core/NamedSearch.cpp
  src/Core/NamedSearch.h
Labels: gui / workflow request, P3

#4500 Fixes windows Qt5.15 build error at VideoWindow line 403
  src/Train/VideoWindow.cpp
Labels: bug

#4502 Error found in GColor function readConfig
  src/Gui/Colors.cpp
Labels: bug

#4503 Remove duplicate theme color code
  src/Gui/Colors.cpp
  src/Gui/Colors.h
  src/Gui/Pages.cpp
Labels: refactoring

#4501 Corrections to qt colors passed to GColor macro
  src/Charts/OverviewItems.h
  src/Metrics/ExtendedCriticalPower.cpp
Labels: refactoring

#4509 Fixed crash on startup if no power zones for bikes are defined
  src/Metrics/Zones.cpp
  src/Train/PowerZonesWidget.cpp
  src/Train/TrainSidebar.cpp
Labels: crash, P0
