Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2024-02, with the labels that each got.

#4444 Charts/PfPvPlot (QA): allow vertical scales up to 2500N
  src/Charts/PfPvPlot.cpp
Labels: charting error, P3

#4445 Fixed some valgrind findings
  src/Charts/AllPlot.cpp
  src/Charts/CPPlot.cpp
  src/Charts/GoldenCheetah.cpp
  src/Charts/GoldenCheetah.h
  src/Charts/HrPwPlot.cpp
  src/Charts/HrPwPlot.h
  src/Charts/OverviewItems.cpp
  src/Charts/OverviewItems.h
  src/Charts/PowerHist.cpp
  src/Charts/ScatterWindow.h
  src/Charts/TreeMapPlot.h
  src/Core/DataFilter.h
  src/FileIO/RideFile.cpp
  src/Gui/ChartSpace.h
  src/Train/ErgFilePlot.h
Labels: refactoring

#4448 Initialized mode when parsing a zwo-file
  src/Train/ErgFile.cpp
Labels: training view, bug, P3
