Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2024-04, with the labels that each got.

#4462 ErgFile: Coalescing neighbouring sections
  src/Core/Settings.h
  src/Gui/Pages.cpp
  src/Gui/Pages.h
  src/Train/ErgFile.cpp
  src/Train/ErgFile.h
  src/Train/TrainSidebar.cpp
  src/Train/WorkoutWindow.cpp
  src/Train/WorkoutWindow.h
Labels: function request, training view, P3

#2927 Add ignore zeros LTM setting
  src/Charts/LTMPlot.cpp
  src/Charts/LTMSettings.cpp
  src/Charts/LTMSettings.h
  src/Charts/LTMTool.cpp
  src/Charts/LTMTool.h
Labels: chart type request, P2

#4417 Added a configurable grayscale filter to RideMapWindow
  src/Charts/RideMapWindow.cpp
  src/Charts/RideMapWindow.h
  src/Core/Settings.h
Labels: chart type request, P3

#3793 Zoomed Elevation widget
  src/Resources/xml/video-layout.xml
  src/Train/MeterWidget.cpp
  src/Train/MeterWidget.h
  src/Train/VideoLayoutParser.cpp
  src/Train/VideoWindow.cpp
Labels: gui / workflow request, training view, P2

#4470 Improved search/filter box drop down menu icon
  src/Gui/SearchBox.cpp
Labels: gui / cosmetic error, P3

#4478 Changed the standard colors for compare-mode
  src/Gui/Colors.cpp
  src/Gui/Colors.h
  src/Gui/ComparePane.cpp
Labels: gui / workflow request, P2

#4303 Added support for old Daum devices before 2001
  src/Train/Daum.cpp
Labels: device support request, training view, P2

#4479 Ergmode: Coloring by powerzones in ErgFilePlot
  src/Train/ErgFile.cpp
  src/Train/ErgFile.h
  src/Train/ErgFilePlot.cpp
  src/Train/ErgFilePlot.h
  src/Train/WorkoutPlotWindow.cpp
  src/Train/WorkoutPlotWindow.h
Labels: chart type request, training view, P2

#4382 show/hide interval settings based on selection
  src/Charts/CriticalPowerWindow.cpp
  src/Charts/CriticalPowerWindow.h
Labels: gui / workflow request, P3

#4482 Initializing AllPlot::isPanning to false
  src/Charts/AllPlot.h
Labels: bug
