Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2024-01, with the labels that each got.

#3842 Use QtBluetooth enums from their namespace
  src/Train/BT40Device.cpp
  src/Train/VMProConfigurator.cpp
Labels: QT6 Refactor

#3916 Replace QString::null by QString()
  src/Charts/AllPlotSlopeCurve.h
  src/Charts/CpPlotCurve.h
  src/Charts/IndendPlotMarker.h
Labels: QT6 Refactor

#3920 Replace QLists toSet() method by QSet constructor
  src/Core/Specification.h
  src/Gui/LTMSidebar.cpp
Labels: QT6 Refactor

#3921 Replace QFontMetrics::width by QFontMetrics::horizontalAdvance
  contrib/qtsolutions/codeeditor/codeeditor.cpp
  src/Charts/AerolabWindow.cpp
  src/Charts/AllPlot.cpp
  src/Charts/ChartBar.cpp
  src/Charts/LTMTool.cpp
  src/Charts/OverviewItems.cpp
  src/Charts/RideEditor.cpp
  src/Cloud/CloudService.cpp
  src/Core/UserData.cpp
  src/Gui/EditUserMetricDialog.cpp
  src/Train/MeterWidget.cpp
Labels: QT6 Refactor

#3919 Use hex and endl from Qt namespace
  src/Charts/CPPlot.cpp
  src/FileIO/JouleDevice.cpp
  src/FileIO/MacroDevice.cpp
  src/FileIO/PowerTapDevice.cpp
  src/Train/BT40Device.cpp
  src/Train/WorkoutWizard.cpp
  src/Train/WorkoutWizard.h
Labels: QT6 Refactor

#3923 Replace QList::swap by QList::swapItemsAt
  src/Charts/AllPlotWindow.cpp
  src/Charts/LTMTool.cpp
Labels: QT6 Refactor

#3924 Replace QTime by QElapsedTimer to measure timings
  src/Charts/CPPlot.cpp
  src/Charts/LTMPlot.cpp
  src/Core/DataFilter.cpp
  src/Core/RideItem.cpp
  src/FileIO/RideFileCache.cpp
  src/Gui/SolveCPDialog.cpp
  src/Metrics/CPSolver.cpp
  src/Metrics/PMCData.cpp
  src/Metrics/UserMetric.cpp
  src/Metrics/WPrime.cpp
  src/Train/TrainSidebar.cpp
  src/Train/TrainSidebar.h
Labels: QT6 Refactor

#3922 Replace QDate::shortDayName by QLocale::dayName
  src/Charts/LTMPlot.h
  src/Core/GcCalendarModel.h
Labels: QT6 Refactor

#3925 Initialize QFlags by default constructor
  src/Charts/LTMTool.cpp
  src/Gui/GcWindowLayout.cpp
  src/Gui/Pages.cpp
  src/Metrics/RideMetadata.cpp
Labels: QT6 Refactor

#3926 Replace qVariantFromValue by QVariant::fromValue
  src/Gui/AnalysisSidebar.cpp
  src/Gui/SolveCPDialog.cpp
Labels: QT6 Refactor

#3927 Change QDate to QDateTime conversions, specifying time
  src/Charts/LTMPlot.cpp
  src/FileIO/MeasuresCsvImport.cpp
  src/FileIO/SrmRideFile.cpp
Labels: QT6 Refactor

#3934 Specify encoding when communicating with OAuth
  src/Cloud/OAuthDialog.cpp
Labels: QT6 Refactor

#3932 Specify encoding when communicating with TodaysPlan
  src/Cloud/TodaysPlan.cpp
  src/Cloud/TodaysPlanBodyMeasures.cpp
  src/Train/TodaysPlanWorkoutDownload.cpp
Labels: QT6 Refactor

#3933 Specify encoding when communicating with DropBox
  src/Cloud/Dropbox.cpp
Labels: QT6 Refactor

#3935 Specify text encoding in several places
  src/Core/Measures.cpp
  src/Core/RideItem.cpp
  src/FileIO/JsonRideFile.y
  src/Gui/Colors.cpp
  src/Metrics/RideMetadata.cpp
Labels: QT6 Refactor

#3936 Replace qStableSort by std::stable_sort
  src/Core/RideCache.cpp
  src/Gui/RideNavigatorProxy.h
Labels: QT6 Refactor

#3940 Use QPainter::setTransform instead of QPainter::setMatrix
  src/Charts/LogTimeScaleDraw.cpp
Labels: QT6 Refactor

#3941 Replace QColor::dark by QColor::darker and light by lighter
  contrib/qxt/src/qxtspanslider.cpp
Labels: QT6 Refactor

#3971 Fix QDir initialization
  src/Core/Athlete.cpp
Labels: QT6 Refactor

#3947 QSet::toList is deprecated - adapt code
  src/Gui/LTMSidebar.cpp
Labels: QT6 Refactor

#3944 QString::sprintf is deprecated - adapt code
  src/Metrics/ExtendedCriticalPower.cpp
Labels: QT6 Refactor

#3945 QTableWidgetItem::setBackgroundColor is deprecated - adapt code
  src/Gui/RideImportWizard.cpp
Labels: QT6 Refactor

#3943 QWebEngineDownloadItem::path is deprecated - adapt code
  src/Train/WebPageWindow.cpp
Labels: QT6 Refactor

#3952 MidButton has been renamed to MiddleButton
  src/Charts/AllPlotWindow.cpp
Labels: QT6 Refactor

#3951 Replace QPalette::Background by QPalette::Window
  deprecated/OverviewWindow.cpp
  deprecated/PerformanceManagerWindow.cpp
  deprecated/RaceRider.cpp
  src/Charts/AerolabWindow.cpp
  src/Charts/AllPlot.cpp
  src/Charts/AllPlotInterval.cpp
  src/Charts/AllPlotWindow.cpp
  src/Charts/CriticalPowerWindow.cpp
  src/Charts/DiaryWindow.cpp
  src/Charts/GenericChart.cpp
  src/Charts/HrPwPlot.cpp
  src/Charts/LTMWindow.cpp
  src/Charts/RideEditor.cpp
  src/Gui/ChartSpace.cpp
  src/Gui/Colors.cpp
  src/Metrics/RideMetadata.cpp
  src/Planning/PlanningWindow.cpp
  src/Train/WorkoutWindow.cpp
Labels: QT6 Refactor

#3954 adapt SSL protocol name
  contrib/httpserver/httpconnectionhandlerpool.cpp
Labels: QT6 Refactor

#3975 Use factory method for QLowEnergyController
  src/Train/BT40Device.cpp
Labels: QT6 Refactor

#3965 Qt6: add QStringRef include
  src/FileIO/JsonRideFile.h
Labels: QT6 Refactor

#3962 Qt6: adapt checksum methods
  src/Metrics/UserMetricSettings.h
Labels: QT6 Refactor

#3964 Qt6: replace toTime_t by toSecsSinceEpoch
  src/ANT/ANT.h
  src/Cloud/RideWithGPS.cpp
  src/Cloud/WithingsDownload.cpp
  src/Core/RideItem.cpp
  src/FileIO/BinRideFile.cpp
  src/FileIO/CsvRideFile.cpp
  src/FileIO/FitRideFile.cpp
  src/FileIO/JouleDevice.cpp
  src/FileIO/MacroDevice.cpp
  src/FileIO/PowerTapDevice.cpp
  src/FileIO/QuarqParser.cpp
  src/FileIO/RawRideFile.cpp
  src/FileIO/SrmDevice.cpp
  src/FileIO/SrmRideFile.cpp
  src/FileIO/SyncRideFile.cpp
  src/Gui/RideNavigator.cpp
  src/R/RTool.cpp
  src/Train/TrainDB.cpp
Labels: QT6 Refactor

#3967 Qt6: Remove call to qRegisterMetaTypeStreamOperators
  src/Charts/LTMSettings.h
Labels: QT6 Refactor

#3968 QWebEnginePage::view was removed
  src/Charts/LTMWindow.cpp
  src/Charts/PythonChart.cpp
  src/Charts/RideMapWindow.cpp
  src/Cloud/OAuthDialog.cpp
  src/Core/GcUpgrade.cpp
  src/Gui/GcCrashDialog.cpp
  src/Train/LiveMapWebPageWindow.cpp
  src/Train/WebPageWindow.cpp
Labels: QT6 Refactor

#3980 workaround circular dependency for qt6
  src/Charts/GoldenCheetah.h
Labels: QT6 Refactor

#3969 Qt6: Remove usage of QHashIterator
  src/Charts/LTMPlot.cpp
Labels: QT6 Refactor

#3974 QMap::const_iterator cannot do +1 any more. Workaround this.
  src/FileIO/Snippets.cpp
Labels: QT6 Refactor

#3979 Some more workarounds about iterators which cannot +1
  src/Core/RideDB.y
  src/FileIO/JsonRideFile.y
Labels: QT6 Refactor

#3981 Add some necessary includes
  src/FileIO/TTSReader.cpp
  src/Train/WebPageWindow.h
Labels: QT6 Refactor

#3970 Some fixes around QString
  src/Core/Utils.cpp
  src/Core/main.cpp
  src/FileIO/JouleDevice.cpp
  src/FileIO/JsonRideFile.h
  src/FileIO/JsonRideFile.l
  src/FileIO/MacroDevice.cpp
  src/FileIO/MoxyDevice.cpp
  src/FileIO/PolarRideFile.cpp
  src/FileIO/PowerTapDevice.cpp
Labels: QT6 Refactor

#3963 Qt6: remove QStringList declaration
  src/Core/Utils.h
Labels: QT6 Refactor

#3988 Some fixes around margins for Qt6
  deprecated/NewMainWindow.cpp
  src/Charts/UserChart.cpp
  src/Gui/GcWindowLayout.cpp
Labels: QT6 Refactor

#3977 There are two overloads for QStringList and QVector<QString>
  src/Charts/GenericChart.cpp
  src/Charts/GenericChart.h
Labels: QT6 Refactor

#3972 Qt6: QSettings defaults to UTF-8, no setIniCodec necessary
  src/Core/Measures.cpp
Labels: QT6 Refactor

#3960 Qt6: Add QRegExp include and adapt usage
  src/Charts/LTMPopup.cpp
  src/Charts/RideEditor.cpp
  src/Cloud/AddCloudWizard.cpp
  src/Cloud/CalendarDownload.cpp
  src/Cloud/CloudDBChart.cpp
  src/Cloud/CloudDBUserMetric.cpp
  src/Core/Route.cpp
  src/Core/Settings.cpp
  src/Core/TimeUtils.cpp
  src/FileIO/MeasuresCsvImport.cpp
  src/FileIO/RideFile.h
  src/FileIO/TxtRideFile.cpp
  src/Gui/ComparePane.cpp
  src/Gui/MainWindow.cpp
  src/Gui/MergeActivityWizard.cpp
  src/Gui/Pages.cpp
  src/Gui/RideImportWizard.cpp
  src/Gui/RideNavigator.cpp
  src/Metrics/HrZones.cpp
  src/Metrics/SpecialFields.cpp
  src/Train/KettlerConnection.cpp
  src/Train/RealtimeController.cpp
Labels: QT6 Refactor

#4431 Qt6: Removed an unused timer
  src/Train/Fortius.cpp
Labels: QT6 Refactor

#3949 Qt6: adapt build system to accept Qt6
  src/src.pro
Labels: QT6 Refactor

#4432 Qt6: Removed one of two overloads for QVector<QString> and QStringList
  src/Core/DataFilter.h
Labels: QT6 Refactor

#4433 Qt6: Using one more Bluetooth enum from its namespace
  src/Train/BT40Device.cpp
Labels: QT6 Refactor

#4437 Qt6: Fixed a crash in RideMapWindow
  src/Charts/RideMapWindow.cpp
Labels: bug, QT6 Refactor

#4435 Qt6: Prevent the use of a deleted QVariant constructor
  src/Gui/Pages.cpp
Labels: QT6 Refactor

#4436 Qt6: Fixed connections
  src/Charts/UserChart.cpp
  src/Gui/DownloadRideDialog.cpp
  src/Gui/DownloadRideDialog.h
Labels: QT6 Refactor

#4440 bluetooth FTMS fix: if condition was always false, so no speed was re…
  src/Train/BT40Device.cpp
Labels: device support error, training view, P3
