Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2024-03, with the labels that each got.

#4452 Qt6: Fixed flickering MainWindow
  src/Charts/RideMapWindow.cpp
  src/Gui/MainWindow.cpp
Labels: QT6 Refactor

#4456 FitRideFile - Added support for new message structure
  src/FileIO/FitRideFile.cpp
Labels: file format request, P1

#4453 Replaced the icons in the TrainBottomBar
  src/Resources/application.qrc
  src/Resources/images/breeze/dark/back.svg
  src/Resources/images/breeze/dark/cal.svg
  src/Resources/images/breeze/dark/down.svg
  src/Resources/images/breeze/dark/ffwd.svg
  src/Resources/images/breeze/dark/fwd.svg
  src/Resources/images/breeze/dark/lap.svg
  src/Resources/images/breeze/dark/offline.svg
  src/Resources/images/breeze/dark/online.svg
  src/Resources/images/breeze/dark/pause.svg
  src/Resources/images/breeze/dark/play.svg
  src/Resources/images/breeze/dark/rewind.svg
  src/Resources/images/breeze/dark/stop.svg
  src/Resources/images/breeze/dark/unknown.svg
  src/Resources/images/breeze/dark/up.svg
  src/Resources/images/breeze/light/back.svg
  src/Resources/images/breeze/light/cal.svg
  src/Resources/images/breeze/light/down.svg
  src/Resources/images/breeze/light/ffwd.svg
  src/Resources/images/breeze/light/fwd.svg
  src/Resources/images/breeze/light/lap.svg
  src/Resources/images/breeze/light/offline.svg
  src/Resources/images/breeze/light/online.svg
  src/Resources/images/breeze/light/pause.svg
  src/Resources/images/breeze/light/play.svg
  src/Resources/images/breeze/light/rewind.svg
  src/Resources/images/breeze/light/stop.svg
  src/Resources/images/breeze/light/unknown.svg
  src/Resources/images/breeze/light/up.svg
  src/Resources/images/oxygen/back.png
  src/Resources/images/oxygen/cal.png
  src/Resources/images/oxygen/down.png
  src/Resources/images/oxygen/equalizer.png
  src/Resources/images/oxygen/ffwd.png
  src/Resources/images/oxygen/fwd.png
  src/Resources/images/oxygen/lap.png
  src/Resources/images/oxygen/open.png
  src/Resources/images/oxygen/pause.png
  src/Resources/images/oxygen/play.png
  src/Resources/images/oxygen/power-off.png
  src/Resources/images/oxygen/power-on.png
  src/Resources/images/oxygen/rewind.png
  src/Resources/images/oxygen/save.png
  src/Resources/images/oxygen/stop.png
  src/Resources/images/oxygen/up.png
  src/Train/TrainBottom.cpp
  src/Train/TrainBottom.h
  src/Train/TrainSidebar.cpp
Labels: gui / workflow request, training view, P2

#3413 Download Strava Routes as Workouts
  src/Cloud/OAuthDialog.cpp
  src/Gui/HelpWhatsThis.cpp
  src/Gui/HelpWhatsThis.h
  src/Gui/MainWindow.cpp
  src/Gui/MainWindow.h
  src/Train/StravaRoutesDownload.cpp
  src/Train/StravaRoutesDownload.h
  src/Train/TrainSidebar.cpp
  src/src.pro
Labels: gui / workflow request, P2, cloud

#4461 Multiple custom power curves 4460
  src/Gui/Pages.cpp
  src/Train/DeviceConfiguration.cpp
Labels: training view, bug, P3

#4455 Fixed rounding error when loading and saving ERG files
  src/Train/ErgFile.cpp
Labels: training view, bug, P3

#4383 Fix various typos
  CONTRIBUTING.md
  INSTALL-LINUX
  INSTALL-MAC
  INSTALL-WIN32
  appveyor.yml
  test/charts/WattOverDuration-PythonCompare.gchart
  travis/osx/after_success.sh
  travis/osx/before_script.sh
Labels: documentation error

#4463 Fix typos in Spanish translation
  src/Resources/translations/gc_es.ts
Labels: translation

#4464 Bound global action to QKeySequence::Quit
  src/Gui/MainWindow.cpp
  src/Gui/SaveDialogs.cpp
Labels: gui / workflow request, P3
