Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2025-07, with the labels that each got.

#4666 Add planned workouts / activities
  src/Gui/Colors.cpp
  src/Gui/Colors.h
  src/Gui/MainWindow.cpp
  src/Gui/MainWindow.h
  src/Gui/ManualActivityWizard.cpp
  src/Gui/ManualActivityWizard.h
  src/Train/InfoWidget.cpp
  src/Train/InfoWidget.h
  src/Train/WorkoutFilterBox.cpp
  src/Train/WorkoutFilterBox.h
Labels: P1, Planning

#4671 Update Spanish translation
  src/Resources/translations/gc_es.ts
Labels: translation

#4674 Add the override classifier for some overridden functions
  src/Charts/GoldenCheetah.h
  src/Charts/OverviewItems.h
  src/Gui/AbstractView.h
  src/Gui/Perspective.h
Labels: refactoring

#4668 Improve support for CORE sensor
  src/Gui/Colors.cpp
  src/Gui/Colors.h
  src/Train/DialWindow.cpp
  src/Train/DialWindow.h
  src/Train/NullController.cpp
  src/Train/NullController.h
  src/Train/RealtimeData.cpp
  src/Train/RealtimeData.h
  src/Train/WorkoutWidget.cpp
  src/Train/WorkoutWidget.h
  src/Train/WorkoutWidgetItems.cpp
  src/Train/WorkoutWindow.cpp
  src/Train/WorkoutWindow.h
Labels: training view, feature request, P2
