Repository GoldenCheetah/GoldenCheetah, pull requests merged in 2025-01, with the labels that each got.

#4590 Batch processing metadata auto completion field
  src/Gui/BatchProcessingDialog.cpp
  src/Gui/BatchProcessingDialog.h
Labels: gui / workflow request, P3

#4601 Enable compiling VideoWindow with QT6 toolset
  src/Gui/GcCrashDialog.cpp
  src/Train/VideoWindow.cpp
  src/Train/VideoWindow.h
  src/gcconfig.pri.in
Labels: QT6 Refactor

#4602 Store coretemp quality data
  src/ANT/ANTChannel.cpp
  src/ANT/ANTMessage.cpp
  src/Train/RealtimeData.cpp
Labels: training view

#4603 Added 'Context' to VideoLayoutParser, resolving crash d18f24c, fixing #4484
  src/Train/VideoLayoutParser.cpp
  src/Train/VideoLayoutParser.h
  src/Train/VideoWindow.cpp
Labels: bug, QT6 Refactor

#4596 Move workout filter to the toolbar
  src/Core/Context.h
  src/Gui/HelpWhatsThis.cpp
  src/Gui/HelpWhatsThis.h
  src/Gui/MainWindow.cpp
  src/Gui/MainWindow.h
  src/Train/TrainSidebar.cpp
  src/Train/TrainSidebar.h
  src/Train/WorkoutFilterBox.cpp
  src/Train/WorkoutFilterBox.h
  src/src.pro
Labels: gui / workflow request

#4607 Fix crash caused by WorkoutFilterBox (see #4606)
  src/Train/WorkoutFilterBox.cpp
  src/Train/WorkoutFilterBox.h
Labels: crash, training view

#4610 Update GC icon to match the new splash screen
  src/Resources/images-src/gc.svg
  src/Resources/images/gc.icns
  src/Resources/images/gc.ico
  src/Resources/images/gc.png
Labels: gui / cosmetic error

#4611 Improve CoreTemp data
  src/ANT/ANT.cpp
  src/ANT/ANT.h
  src/ANT/ANTChannel.cpp
  src/ANT/ANTChannel.h
  src/ANT/ANTMessage.cpp
  src/ANT/ANTMessage.h
  src/ANT/ANTlocalController.cpp
  src/FileIO/CsvRideFile.cpp
  src/Train/RealtimeData.cpp
  src/Train/RealtimeData.h
  src/Train/TrainSidebar.cpp
  src/Train/TrainSidebar.h
Labels: device support request, training view, P2
